# Generated by Django 2.0.7 on 2018-08-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
